version: "3.8"

services:
  aggregator:
    build: .
    container_name: x-ui-aggregator
    restart: always
    env_file:
      - .env
    ports:
      - "${SITE_PORT}:${SITE_PORT}"
    volumes:
      - ${PATH_SSL_KEY}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ${PATH_SSL_KEY}/privkey.pem:/etc/nginx/ssl/privkey.pem