services:
  nginx-proxy:
    build: .
    container_name: 3x-ui-sub-aggregator
    ports:
      - "1222:443"
    env_file:
      - .env
    volumes:
      - ./config_fetcher.lua:/etc/nginx/lua/config_fetcher.lua
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped
